# Generated by Django 2.2.5 on 2020-01-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='<b>あなたの名前を入力してください</b>', max_length=64, verbose_name='名前')),
                ('message', models.CharField(help_text='<u>メッセージを入力してください</u>', max_length=255, verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
        ),
    ]
