# Generated by Django 2.2.5 on 2020-01-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
